repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        files: 'aiohttp_retry'
        stages:
        - commit
        - push
    -   id: autopep8
        files: 'tests'
        stages:
        - commit
        - push
